export const ACTIVE_ITEM = 'ACTIVE_ITEM';
export const ADD_ITEM = 'ADD_ITEM';
export const DEL_ITEM = 'DEL_ITEM';

export const ADD_RESOURCE = 'ADD_RESOURCE';
export const REMOVE_RESOURCE = 'REMOVE_RESOURCE';
export const UPDATE_RESOURCE = 'UPDATE_RESOURCE';

export const UPDATE_RESOURCE_DATA = 'UPDATE_RESOURCE_DATA';
export const SYNCING = "SYNCING";
export const CHECK_ITEMS = "CHECK_ITEMS";
export const MUTI_SYNCING = "MUTI_SYNCING";
export const ADD_BUCKET = "ADD_BUCKET";
export const MODIFY_BUCKET = "MODIFY_BUCKET";
export const ACTIVE_BUCKET = "ACTIVE_BUCKET";
export const UPLOAD_CONFIRM = "UPLOAD_CONFIRM";
export const UPLOAD_PERCENT = "UPLOAD_PERCENT";