export const USERINFO_LOGIN_SUCCESS = 'USERINFO_LOGIN_SUCCESS';
export const USERINFO_LOGIN_FAILURE = 'USERINFO_LOGIN_FAILURE';
export const USERINFO_LOGIN_OUT = 'USERINFO_LOGIN_OUT';
export const UPDATE_TOKEN = 'UPDATE_TOKEN';